### ISSUE TITLE
Extract sender/auther's name

### ISSUE THREAD

**Issue by ryotsu** [Flying-Toast/yugo#15]
Hey,

Is there any way to extract the name from the FROM or sender address?
Such as `John Doe` from `John Doe <johndoe@example.com>`.

I see that the `FROM` field has been dropped and the parser ignores the name. https://github.com/Flying-Toast/yugo/blob/d6574fae27ae3e2b915e2d1d4e7ab17b72e65df6/lib/yugo/client.ex#L470  https://github.com/Flying-Toast/yugo/blob/d6574fae27ae3e2b915e2d1d4e7ab17b72e65df6/lib/yugo/parser.ex#L287

**Comment by Flying-Toast** [comment]
Correct, right now there's no way to work with FROM or get the name. There's no good reason for this other than I didn't originally need that functionality when I wrote the library :-)

I'd be happy to review any PRs if you'd like to take a stab at this. If not, I can probably get around to it sometime in the coming week.

**Comment by Flying-Toast** [comment]
Ha, guess I did have time for that. Can you take a look at v1.0.0?

**Comment by ryotsu** [comment]
Great! Works really well. Thank you for this excellent library!
