### ISSUE TITLE
Add additional mailbox manipulation commands (MOVE, LIST, etc)

### ISSUE THREAD

**Issue by bkono** [Flying-Toast/yugo#24]
Love the library, nicely done. 

Its current focus is clearly around read-only, receiving of messages. I've actually forked it and started adding some additional functionality around LIST and MOVE specifically, and will need to add fetching of prior messages and creation of mailboxes/folders as well. 

Are you open to PRs adding additional, non-receiving, functionality? Wanted to check-in on your goals with the lib first before investing in getting my early spikes to PR ready. If yes, any specific requests or contributor guidelines besides the norm (doc comments, tests etc)?

**Comment by Flying-Toast** [comment]
Hi!

My initial use case for the library was indeed very read-only, but I’d be more than happy to review a PR for additional features to make the library more complete.

Aside from the norm, all I’d say is to try and keep the details of IMAP at least somewhat abstracted away so that users need not be familiar with the intricacies of the IMAP spec in order to use the library.

Thanks!

**Comment by bkono** [comment]
Awesome, so far I've added LIST, MOVE, and CREATE with tests, as well as some smaller related updates (slightly improved IDLE handling, flowing seqnum through the message to support a very easy MOVE workflow, etc). Keeping the API surface area reasonably abstracted from IMAP, since I don't like having to remember much of it either 😆. Will finish confirming they are working as expected, and then split up into a few PRs to keep it from being overwhelming.

**Comment by alappe** [comment]
@bkono Would you still consider adding your functionality to list/fetch messages?

**Comment by bkono** [comment]
> [@bkono](https://github.com/bkono) Would you still consider adding your functionality to list/fetch messages?

Hey @alappe - haven't been back to clean up my changes to the lib since handing off my original project using it. Since I'd referenced my branch in another issue, figured it was worth giving it a quick rebase and update. You can see my changes [here](https://github.com/Flying-Toast/yugo/compare/master...bkono:yugo:feat/fetch-move-list-etc) ... feel free to dig into that [feat/fetch-move-list-etc](https://github.com/bkono/yugo/tree/feat/fetch-move-list-etc) branch. Haven't had a chance to test the rebase, but the only real conflict was on moving from do_init to handle_continue, so I wouldn't expect any major issues there.

Let me know if you run into any trouble with it.

**Comment by bkono** [comment]
Just a heads up, I went ahead and gave it a test run to confirm things were still working as expected. No issues. Since I have another small project I'd like to bring this into, I just opened PR #33 for it.

**Comment by alappe** [comment]
Thank you @bkono and sorry for the delayed response, also to your response on reception that stops. I'll try to test it for my case the next days. Looks and sounds great!
